### PR TITLE
Feature #16 auto doc

### PR DESCRIPTION
**Pull request by FrankKr**
Added documentation functionality. Result can be found here: https://alliander-opensource.github.io/short-term-forecasting/index.html
It can be improved further, but for now at least all functions are findable, and the flow works.
E.g: https://alliander-opensource.github.io/short-term-forecasting/stf/stf.model.prediction.xgboost.html

### CODE REVIEW

**Comment by FrankKr** [comment]
answer to this issue:
https://github.com/alliander-opensource/short-term-forecasting/issues/16

**Comment by bremme** [comment]
Just a note, it seems this branch has been branched off main instead of develop.

**Comment by FrankKr** [comment]
Thanks for pointing out!

**Comment by bremme** [comment]
Very nice addition to the project! I already merged develop back in to this branch and fixed some conventions. I also have a couple questions/remarks:

* The duplicated `requirements.txt` file is cumbersome and prone to error, could this not be fixed easily?
* Same for the `ktpbase` empty package.
* The steps in the Github action looks different from the description in the README (in the docs folder)
* Not really clear to me how to run locally
  * I could not find the dependencies (sphinx and sphinx_rtd_theme I guess)
  * Not sure how to deal with all the produced files, they seem to go in the docs root folder and or not part of .gitignore
* Perhaps we need to think about documentation versioning (people might use older versions this package)
* Nice to add a link to the documentation in the Project description and (main) README

**Comment by FrankKr** [comment]
> Very nice addition to the project! I already merged develop back in to this branch and fixed some conventions. I also have a couple questions/remarks:
> 
> * The duplicated `requirements.txt` file is cumbersome and prone to error, could this not be fixed easily?
> * Same for the `ktpbase` empty package.
> * The steps in the Github action looks different from the description in the README (in the docs folder)
> * Not really clear to me how to run locally
>   
>   * I could not find the dependencies (sphinx and sphinx_rtd_theme I guess)
>   * Not sure how to deal with all the produced files, they seem to go in the docs root folder and or not part of .gitignore
> * Perhaps we need to think about documentation versioning (people might use older versions this package)
> * Nice to add a link to the documentation in the Project description and (main) README

Good idea. I incorporated the requirements.txt and ktpbase suggestions.
There are actually two github-actions. One to build the Documentation on Release, and one to check if it can be build on PR. I updated the docs/readme to reflect this
Added the dependencies
updated .gitignore
updated run locally instruction in readme

**Pull request merged**
