### PR TITLE
Patch clarifications to license structure were made

### PR DESCRIPTION
**Pull request by Jonasvdbo**
Improve the license structure for clarification.

### CODE REVIEW

**Review by FrankKr — APPROVED** [review]

**Comment by bremme** [comment]
It looks like various things went wrong with this PR. 

* It should have branched off develop and not main
* It should have been merged with develop first
* The project is not reuse compliant anymore
* (capitals are discouraged in branch names)

We use Gitflow for this project so all features/changes should branch of develop and NOT main. Since we just migrated, our CI/CD had not been integrated into main. So by merging with main directly you miss all CI/CD checks. The changes that were made on the main branch make our project incompatible with the REUSE specifications:

```
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* .github/ISSUE_TEMPLATE/bug_report.md
* .github/ISSUE_TEMPLATE/documentation.md
* .github/ISSUE_TEMPLATE/feature_request.md


# SUMMARY

* Bad licenses: CC-BY-2.5-AU
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: CC-BY-2.5-AU, MIT, MPL-2.0
* Unused licenses:
* Used licenses:
* Read errors: 0
* Files with copyright information: 154 / 157
* Files with license information: 154 / 157

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

**Comment by bremme** [comment]
Some of the RUSE errors on the main branch where already fixed on develop by the way.

**Comment by FrankKr** [comment]
Whoops, I think I did not pay close attention to which was the receiving branch. 
Perhaps I can fix this by releasing our improvements of develop of the last two days to main. We don't have a strict release policy yet. @bremme sounds good?

**Comment by Jonasvdbo** [comment]
@bremme You are fully correct. I'm enthoaustime to make more clair which license is the main license and also make sure github automatically recognizes the correct license. I forgot the reuse compliant check. I will submit a new pull to fix this. Also I will in the future submit to development branch.

**Comment by Jonasvdbo** [comment]
@bremme and @FrankKr The following two pull request should fix the above mentions things: https://github.com/alliander-opensource/short-term-forecasting/pull/27 & https://github.com/alliander-opensource/short-term-forecasting/pull/28

**Pull request merged**
